### ISSUE TITLE
Maybe some minor issue in visual.py?

### ISSUE THREAD

**Issue by Hecate2** [MorvanZhou/mnistGANs#1]
When I run `gan.py`, I had an excpetion at line 116 of `visual.py`, in the function `_save_gan`. The variable `imgs` is of shape (100,28,28,1), and `imgs[i]` of shape (28,28,1) cannot be accepted by `plt.imshow`. I just changed it to `imgs[i,:,:,0]`.

**Comment by MorvanZhou** [comment]
Which version of Matplotlib do you use? Does matplotlib==3.3.2 solves your problem?

**Comment by Hecate2** [comment]
I used 3.2.X, and 3.3.2 still did not work. I cannot really locate any doc of matplotlib 3.3.2, but according to docs of 3.3.3, an image of shape (:,:,1) is not supported by imshow.
https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html

**Comment by MorvanZhou** [comment]
This issue has been solved now in the latest commit.
